module.exports = {
  env: {
    browser: true,
    node: true,
    es6: true,
  },
  reportUnusedDisableDirectives: true,
  ignorePatterns: [
    '*.min.*',
    '*.d.ts',
    'CHANGELOG.md',
    'dist',
    'LICENSE*',
    'output',
    'out',
    'coverage',
    'public',
    'temp',
    'package-lock.json',
    'pnpm-lock.yaml',
    'yarn.lock',
    '__snapshots__',
    '!.github',
    '!.vitepress',
    '!.vscode',
  ],
  extends: ['eslint:recommended', 'airbnb-base', 'plugin:import/recommended'],
  rules: {
    'no-console': 'off',
    'no-tabs': 'off',
    'no-multi-assign': 'off',
    'no-param-reassign': 'off',
    'no-plusplus': 'off',
    'no-shadow': 'warn',
    'no-underscore-dangle': 'warn',
    'no-unused-vars': 'warn',
    'no-unused-expressions': 'off',
    'no-useless-escape': 'off',
    'eqeqeq': 'warn',
    'import/prefer-default-export': 'off',
    'import/extensions': 'off',
    'array-callback-return': 'off',
    'consistent-return': 'off',
    'guard-for-in': 'off',
    'func-names': 'off',
    semi: ['error', 'never'],
    'max-len': ['error', { code: 120 }],
    'import/no-unresolved': 'off',
    'import/no-extraneous-dependencies': ['error', {
      devDependencies: true, optionalDependencies: false, peerDependencies: false, bundledDependencies: false,
    }],
    'no-use-before-define': ['error', {
      functions: false, classes: false, variables: true, allowNamedExports: true,
    }],
  },
}
